# Copyright (C) 2021 Zac Sweers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[versions]
agp = "8.11.0"
androidx-lint-gradle = "1.0.0-alpha05"
anvil = "0.4.1"
atomicfu = "0.29.0"
autoService = "1.1.1"
circuit = "0.30.0"
classgraph = "4.8.181"
compose-jb = "1.8.2"
dagger = "2.57.1"
gjf = "1.28.0"
jdk = "21"
junit5 = "5.13.4"
jvmTarget = "21"
kct = "0.8.0"
kotlin = "2.2.10"
kotlinInject = "0.8.0"
kotlinInject-anvil = "0.1.6"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
ksp = "2.2.10-2.0.2"
ktfmt = "0.56"
ktor = "3.2.2"
okhttp = "5.1.0"
okio = "3.16.0"
pluginId = "dev.zacsweers.metro.compiler"
poko = "0.19.3"
wire = "5.4.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
anvil = { id = "dev.zacsweers.anvil", version.ref = "anvil" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-jb" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.7" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0-Beta" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
shadow = { id = "com.gradleup.shadow", version = "9.1.0" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
testkit = { id = "com.autonomousapps.testkit", version = "0.16" }
wire = { id = "com.squareup.wire", version.ref = "wire" }

[libraries]
androidx-activity = "androidx.activity:activity-compose:1.10.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-compose-material3 = "androidx.compose.material3:material3:1.3.2"
androidx-compose-materialNavigation = "androidx.compose.material:material-navigation:1.9.0"
androidx-core = "androidx.core:core-ktx:1.17.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.8.9"
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.9.3"
androidx-lint-gradle = {  module = "androidx.lint:lint-gradle", version.ref = "androidx-lint-gradle" }
androidx-material3 = "com.google.android.material:material:1.13.0"
androidx-navigationCompose = "androidx.navigation:navigation-compose:2.9.3"
androidx-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.3"
androidx-work = "androidx.work:work-runtime:2.10.3"

anvil-annotations = { module = "dev.zacsweers.anvil:annotations", version.ref = "anvil" }
anvil-annotations-optional = { module = "dev.zacsweers.anvil:annotations-optional", version.ref = "anvil" }

autoService = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.2.0" }

atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
clikt = "com.github.ajalt.clikt:clikt:5.0.3"

circuit-codegen = { module = "com.slack.circuit:circuit-codegen", version.ref = "circuit" }
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-runtime = { module = "com.slack.circuit:circuit-runtime", version.ref = "circuit" }
circuit-codegenAnnotations = { module = "com.slack.circuit:circuit-codegen-annotations", version.ref = "circuit" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-jb" }
compose-materialIcons = { module = "org.jetbrains.compose.material:material-icons-core", version = "1.7.3" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-jb" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-jb" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-jb" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

kotlinInject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlinInject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInject" }
kotlinInject-anvil-compiler = { module = "software.amazon.lastmile.kotlin.inject.anvil:compiler", version.ref = "kotlinInject-anvil" }
kotlinInject-anvil-runtime = { module = "software.amazon.lastmile.kotlin.inject.anvil:runtime", version.ref = "kotlinInject-anvil" }
kotlinInject-anvil-runtime-optional = { module = "software.amazon.lastmile.kotlin.inject.anvil:runtime-optional", version.ref = "kotlinInject-anvil" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-annotationsJvm = { module = "org.jetbrains.kotlin:kotlin-annotations-jvm", version.ref = "kotlin" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-compilerTestFramework = { module = "org.jetbrains.kotlin:kotlin-compiler-internal-test-framework", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-aptEmbeddable = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-scriptRuntime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinx-serialization" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1-0.6.x-compat"

# Only present to trigger automatic renovate updates
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
gjf = { module = "com.google.googlejavaformat:google-java-format", version.ref = "gjf" }

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-engine-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

picnic = "com.jakewharton.picnic:picnic:0.7.0"

poko-annotations = { module = "dev.drewhamilton.poko:poko-annotations", version.ref = "poko" }

slf4jNop = "org.slf4j:slf4j-nop:2.0.17"

junit = { module = "junit:junit", version = "4.13.2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
ksp-symbolProcessing = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
ksp-symbolProcessing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-symbolProcessing-commonDeps = { module = "com.google.devtools.ksp:symbol-processing-common-deps", version.ref = "ksp" }
ksp-symbolProcessing-aaEmbeddable = { module = "com.google.devtools.ksp:symbol-processing-aa-embeddable", version.ref = "ksp" }
testkit-support = { module =  "com.autonomousapps:gradle-testkit-support", version = "0.20"}
testkit-truth = { module =  "com.autonomousapps:gradle-testkit-truth", version = "1.6.1"}
truth = { module = "com.google.truth:truth", version = "1.4.4" }
kct = { module = "dev.zacsweers.kctfork:core", version.ref = "kct" }
kct-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kct" }

wire-runtime = { module = "com.squareup.wire:wire-runtime-jvm", version.ref = "wire" }
