name: Development

on:
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_CI: true

permissions:
  checks: write        # Required for publishing test results
  pull-requests: write # Required for PR comments (if enabled later)
  contents: read       # Required for checkout

jobs:
  validate-ktlint:
    name: Validate Ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Ktlint
        uses: ./.github/actions/validate-ktlint

  validate-detekt:
    name: Validate Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Detekt
        uses: ./.github/actions/validate-detekt

  validate-spotless:
    name: Validate Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Spotless
        uses: ./.github/actions/validate-spotless

  validate-licenses:
    name: Validate Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run License Check
        uses: ./.github/actions/validate-licenses

  validate-api:
    name: Validate API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run API Check
        uses: ./.github/actions/validate-api

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Execute Tests
        uses: ./.github/actions/run-tests

  test-samples:
    name: Test Samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Sample Tests
        uses: ./.github/actions/test-samples
